apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
  - path: template/_components
    contents:
      - path: .
        git:
          url: https://github.com/betabitplus/ternforge-template-components.git
          ref: v1.7.5
        includePaths:
          - components/agents/base/**/*
          - components/agents/py-library/**/*
          - components/repository/base/template/.editorconfig
          - components/repository/base/template/LICENSE
          - components/repository/copier/**/*
          - components/project/py/base/**/*
          - components/project/py/library/**/*
          - components/quality/py/**/*
          - components/delivery/updates/**/*
          - components/delivery/ci/py-library/**/*
          - components/delivery/release/library/**/*
        excludePaths:
          - .git
          - .git/**/*
        legalPaths: []
