name: release

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  release:
    uses: betabitplus/ternforge-infra-ci/.github/workflows/release.yml@a669bddb811a69dd6533acc2cae0d30ced415337 # v1.5.1
    with:
      app-client-id: ${{ vars.TERNFORGE_RELEASE_CLIENT_ID }}
      repository: ${{ github.event.repository.name }}
      release-type: simple
      synchronize-python-lock: false
    secrets:
      app-private-key: ${{ secrets.TERNFORGE_RELEASE_PRIVATE_KEY }}
